import React from "react";
import PagePagination from "../components/PagePagination";
import BlogCard from "../components/BlogCard";
import { Input } from "@nextui-org/input";
import { Link } from "@nextui-org/link";

export const metadata = {
  title: "RM | Blog",
  description: "Generated by create next app",
};

async function getBlogs() {
  const res = await fetch("https://www.roomacarthur.dev/api/blogs/");
  return res.json();
}

async function getCategories() {
  const res = await fetch("https://www.roomacarthur.dev/api/blog_categories/");
  return res.json();
}

export default async function blogList() {
  // test data.

  const blogs = await getBlogs();
  // Compile all tags and removing duplicates
  const categories = await getCategories();
  //sort blogs in order of newest to oldest to display newest blog posts at the top.
  const sortedBlogs = blogs.sort(
    (a, b) => new Date(b.published_date) - new Date(a.published_date)
  );
  return (
    <main className="min-h-[80vh] p-4 pt-12 sm:p-12 w-[80%] mx-auto">
      <h1 className="mb-12 text-5xl font-black text-foreground text-center">
        Blog📝
      </h1>
      <div>
        <div className="sm:pl-4 pl-0 mb-4">
          <h2>Welcome to my written work.</h2>
          <p className="font-light">
            {`
            Welcome to my blog – a place where I document my thoughts on
            full-stack development, share insights from my projects, and
            sometimes, just muse about the latest in web technologies. Whether
            you're a fellow developer, a curious learner, or somewhere in
            between, there's a story here for you.`}
          </p>
        </div>
        {/* Page Section*/}
        <div className="flex flex-col sm:flex-row">
          <div className="sm:w-2/3 sm:pr-4">
            {/* blog posts */}
            {sortedBlogs.map((blog, index) => (
              <BlogCard blog={blog} key={index} />
            ))}
            <PagePagination />
          </div>
          {/* Side bar  */}
          <div className="sm:w-1/3 mt-8 mb-8 sm:mb-0 sm:mt-4 border-0 rounded-xl bg-gray-800/70 backdrop-blur p-4 border-t shadow-lg border-foreground/80">
            <div>
              {/* Search bar */}
              <h2 className="mb-4">Search</h2>
              <Input>Search</Input>
            </div>
            <div>
              {/* Categories.*/}
              <h2 className="mb-4 mt-4">Categories</h2>
              {/* loop through categories, duplicates are already removed. */}
              {categories.map((category) => (
                <Link
                  href={`blog/catagories/${category.slug}`}
                  key={category.id}
                >
                  <span className="inline-block mr-2 mb-2 px-4 py-1 rounded-full text-xs font-bold bg-teal-400/10 shadow-md cursor-pointer text-teal-300">
                    {category.name}
                  </span>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
