import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ClientSideGradient from "./components/ClientSideGradient"

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "v2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* background gradient effect */}
        <ClientSideGradient />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
