import { Image } from "@nextui-org/image";
import React from "react";
import { Code } from "@nextui-org/react";

async function getBlog(slug) {
  const res = await fetch(`https://www.roomacarthur.dev/api/blogs/${slug}`);
  return res.json()
}

export const metadata = {
  title: "RM | blog title",
  description: "Generated by create next app",
};

export default async function blogDetail({ params}) {
  const blog = await getBlog( params.slug )
  return (
    <main className="min-h-screen p-4 md:p-12 lg:p-24 w-full mx-auto">
      <h1>{blog.title}</h1>
      <Image
        src={blog.thumbnail}
        isBlurred={true}
        className="h-[300px] mx-auto object-cover"
      ></Image>
      <div dangerouslySetInnerHTML={{ __html: blog.content }} />
    </main>
  );
}
